// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8aye08iGa30R62I7cvQ5j3TA1WhTDRoE',
    appId: '1:114731951529:web:e043c2a19f7c6117fc10b8',
    messagingSenderId: '114731951529',
    projectId: 'info-expense-tracker',
    authDomain: 'info-expense-tracker.firebaseapp.com',
    storageBucket: 'info-expense-tracker.appspot.com',
    measurementId: 'G-9GB60P6NSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXiz8u7FIVlmh278lRRjfE4Z1gplG2C8c',
    appId: '1:114731951529:android:a0552f0f28e31a65fc10b8',
    messagingSenderId: '114731951529',
    projectId: 'info-expense-tracker',
    storageBucket: 'info-expense-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApM3gV8lc0W2icemPmfbdd_lfyI7Yy_6U',
    appId: '1:114731951529:ios:dada25000bc7850cfc10b8',
    messagingSenderId: '114731951529',
    projectId: 'info-expense-tracker',
    storageBucket: 'info-expense-tracker.appspot.com',
    iosBundleId: 'com.example.coffeeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApM3gV8lc0W2icemPmfbdd_lfyI7Yy_6U',
    appId: '1:114731951529:ios:7300fa8402a21148fc10b8',
    messagingSenderId: '114731951529',
    projectId: 'info-expense-tracker',
    storageBucket: 'info-expense-tracker.appspot.com',
    iosBundleId: 'com.example.coffeeapp.RunnerTests',
  );
}
